services:
  scala-server:
    build:
      context: ./proto/scala-grpc-sandbox
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    environment:
      GRPC_PORT: "9091"

  python-tests:
    build: .
    depends_on:
      scala-server:
        condition: service_started
    environment:
      GRPC_HOST: scala-server
      GRPC_PORT: "9091"
